/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2024-03-12 06:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<nav class=\"navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("\t<div class=\"text-center navbar-brand-wrapper d-flex align-items-center\">\r\n");
      out.write("\t\t<a class=\"navbar-brand brand-logo\" href=\"index.html\"><img\r\n");
      out.write("\t\t\tsrc=\"adminResources/image/logo.svg\" alt=\"logo\" /></a> <a\r\n");
      out.write("\t\t\tclass=\"navbar-brand brand-logo-mini\" href=\"index.html\"><img\r\n");
      out.write("\t\t\tsrc=\"adminResources/image/logo-mini.svg\" alt=\"logo\" /></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div\r\n");
      out.write("\t\tclass=\"navbar-menu-wrapper d-flex align-items-center justify-content-end\">\r\n");
      out.write("\t\t<button class=\"navbar-toggler navbar-toggler align-self-center\"\r\n");
      out.write("\t\t\ttype=\"button\" data-toggle=\"minimize\">\r\n");
      out.write("\t\t\t<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<ul class=\"navbar-nav mr-lg-2\">\r\n");
      out.write("\t\t\t<li class=\"nav-item nav-search d-none d-lg-block\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-text\" id=\"search\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"mdi mdi-magnify\"></i>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search for anything...\" aria-label=\"search\"\r\n");
      out.write("\t\t\t\t\t\taria-describedby=\"search\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\tclass=\"nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center\"\r\n");
      out.write("\t\t\t\tid=\"messageDropdown\" href=\"#\" data-toggle=\"dropdown\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"mdi mdi-email-outline mx-0\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"messageDropdown\">\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0 font-weight-normal float-left dropdown-header\">Messages</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"adminResources/image/face4.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject ellipsis font-weight-normal\">David\r\n");
      out.write("\t\t\t\t\t\t\t\tGrey</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">The\r\n");
      out.write("\t\t\t\t\t\t\t\tmeeting is cancelled</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"adminResources/image/face2.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject ellipsis font-weight-normal\">Tim\r\n");
      out.write("\t\t\t\t\t\t\t\tCook</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">New\r\n");
      out.write("\t\t\t\t\t\t\t\tproduct launch</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"adminResources/image/face3.jpg\" alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-pic\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content flex-grow\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject ellipsis font-weight-normal\">\r\n");
      out.write("\t\t\t\t\t\t\t\tJohnson</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text text-muted mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\tUpcoming board meeting</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\tclass=\"nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center\"\r\n");
      out.write("\t\t\t\tid=\"notificationDropdown\" href=\"#\" data-toggle=\"dropdown\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"mdi mdi-bell-outline mx-0\"></i> <span class=\"count\"></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"notificationDropdown\">\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-0 font-weight-normal float-left dropdown-header\">Notifications</p>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"preview-icon bg-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-information mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject font-weight-normal\">Application\r\n");
      out.write("\t\t\t\t\t\t\t\tError</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">Just\r\n");
      out.write("\t\t\t\t\t\t\t\tnow</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"preview-icon bg-warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-settings mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject font-weight-normal\">Settings</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\tPrivate message</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"preview-icon bg-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-account-box mx-0\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"preview-item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"preview-subject font-weight-normal\">New user\r\n");
      out.write("\t\t\t\t\t\t\t\tregistration</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"font-weight-light small-text mb-0 text-muted\">2\r\n");
      out.write("\t\t\t\t\t\t\t\tdays ago</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item nav-profile dropdown\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\thref=\"#\" data-toggle=\"dropdown\" id=\"profileDropdown\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"adminResources/image/face5.jpg\" alt=\"profile\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\"> <i class=\"mdi mdi-settings \"></i>\r\n");
      out.write("\t\t\t\t\t\tSettings\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"dropdown-item\"> <i class=\"mdi mdi-logout\"></i>\r\n");
      out.write("\t\t\t\t\t\tLogout\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t<li class=\"nav-item nav-settings d-none d-lg-flex\"><a\r\n");
      out.write("\t\t\t\tclass=\"nav-link\" href=\"#\"> <i class=\"mdi mdi-dots-horizontal\"></i>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<button\r\n");
      out.write("\t\t\tclass=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\"\r\n");
      out.write("\t\t\ttype=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("\t\t\t<span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
