/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2024-03-12 06:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("\t<ul class=\"nav\">\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-clipboard-text-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">Dashboard</span>\r\n");
      out.write("\t\t</a></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\thref=\"pages/widgets/widgets.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-airplay menu-icon\"></i> <span class=\"menu-title\">Widgets</span>\r\n");
      out.write("\t\t</a></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#ui-basic\" aria-expanded=\"false\" aria-controls=\"ui-basic\">\r\n");
      out.write("\t\t\t\t<i class=\"mdi mdi-invert-colors menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">UI Elements</span> <i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"ui-basic\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/accordions.html\">Accordions</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/buttons.html\">Buttons</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/badges.html\">Badges</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/breadcrumbs.html\">Breadcrumbs</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/dropdowns.html\">Dropdowns</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/modals.html\">Modals</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/progress.html\">Progress bar</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/pagination.html\">Pagination</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/tabs.html\">Tabs</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/typography.html\">Typography</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/tooltips.html\">Tooltips</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/popups.html\">Popups</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/notifications.html\">Notifications</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#ui-advanced\" aria-expanded=\"false\" aria-controls=\"ui-advanced\">\r\n");
      out.write("\t\t\t\t<i class=\"mdi mdi-flask-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">Advanced UI</span> <i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"ui-advanced\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/dragula.html\">Dragula</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/clipboard.html\">Clipboard</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/context-menu.html\">Context menu</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/slider.html\">Sliders</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/carousel.html\">Carousel</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/colcade.html\">Colcade</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/ui-features/loaders.html\">Loaders</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#form-elements\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-controls=\"form-elements\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-clipboard-text-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">Form elements</span> <i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"form-elements\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/basic_elements.html\">Basic Elements</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/advanced_elements.html\">Advanced Elements</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/validation.html\">Validation</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/wizard.html\">Wizard</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/text_editor.html\">Text editors</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/forms/code_editor.html\">Code editors</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#charts\" aria-expanded=\"false\" aria-controls=\"charts\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-chart-donut menu-icon\"></i> <span class=\"menu-title\">Charts</span>\r\n");
      out.write("\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"charts\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/chartjs.html\">ChartJs</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/morris.html\">Morris</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/flot-chart.html\">Flot</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/google-charts.html\">Google charts</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/sparkline.html\">Sparkline js</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/c3.html\">C3 charts</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/chartist.html\">Chartists</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/charts/justGage.html\">JustGage</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#tables\" aria-expanded=\"false\" aria-controls=\"tables\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-grid-large menu-icon\"></i> <span class=\"menu-title\">Tables</span>\r\n");
      out.write("\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"tables\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/tables/basic-table.html\">Basic table</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/tables/data-table.html\">Data table</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/tables/js-grid.html\">Js-grid</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/tables/sortable-table.html\">Sortable table</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#icons\" aria-expanded=\"false\" aria-controls=\"icons\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-emoticon-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">Icons</span> <i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"icons\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/icons/flag-icons.html\">Flag icons</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/icons/mdi.html\">Mdi icons</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/icons/font-awesome.html\">Font Awesome</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/icons/simple-line-icon.html\">Simple line icons</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/icons/themify.html\">Themify icons</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#maps\" aria-expanded=\"false\" aria-controls=\"maps\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-map-outline menu-icon\"></i> <span class=\"menu-title\">Maps</span>\r\n");
      out.write("\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"maps\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/maps/mapael.html\">Mapael</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/maps/vector-map.html\">Vector Map</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/maps/google-maps.html\">Google Map</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#general-pages\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-controls=\"general-pages\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-file-outline menu-icon\"></i> <span class=\"menu-title\">General\r\n");
      out.write("\t\t\t\t\tPages</span> <i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"general-pages\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/blank-page.html\"> Blank Page </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/profile.html\"> Profile </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/faq.html\"> FAQ </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/faq-2.html\"> FAQ 2 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/news-grid.html\"> News grid </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/timeline.html\"> Timeline </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/search-results.html\"> Search Results </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/portfolio.html\"> Portfolio </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/invoice.html\"> Invoice </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/pricing-table.html\"> Pricing Table </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/orders.html\"> Orders </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/login.html\"> Login </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/login-2.html\"> Login 2 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/register.html\"> Register </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/register-2.html\"> Register 2 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/lock-screen.html\"> Lockscreen </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/error-404.html\"> Error 404 </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/samples/error-500.html\"> Error 500 </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\thref=\"#apps\" aria-expanded=\"false\" aria-controls=\"apps\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-cube-outline menu-icon\"></i> <span class=\"menu-title\">Apps</span>\r\n");
      out.write("\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"apps\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/apps/email.html\"> Email </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/apps/calendar.html\"> Calendar </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/apps/todo.html\"> Todo List </a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"pages/apps/gallery.html\"> Gallery </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\t\t<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\thref=\"pages/documentation/documentation.html\"> <i\r\n");
      out.write("\t\t\t\tclass=\"mdi mdi-file-document-box-outline menu-icon\"></i> <span\r\n");
      out.write("\t\t\t\tclass=\"menu-title\">Documentation</span>\r\n");
      out.write("\t\t</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
